### PR TITLE
Change number of spaces text colour on hover to red

### PR DESCRIPTION
**Pull request by Lethalmathematix**
Makes it easier to distinguish the number of spaces numbers from your ascii art when it is composed of numbers

### CODE REVIEW

**Comment by TyHil** [comment]
Would using `var(--light2)` fix your problem instead of red? It looks much less intrusive.

Otherwise, I think `#128a74` would be better than red to fit the theme.

**Comment by Lethalmathematix** [comment]
I just checked with `light2`- it's a bit better than `light0`, but I think `#128a74` has better glance-value visibility while typing.

**Comment by TyHil** [comment]
Sound good, thanks for doing this! I'm going to make a change after merging to integrate that color into the style-guide.

Out of curiosity, are you using the site for ASCII art on a typewriter or something else?

**Comment by Lethalmathematix** [comment]
Yep. Was putting some ASCII art on paper using a typewriter.
 Pretty handy to see the number of spaces, and configure the page lines and columns
 
 Thank you for making this!

**Comment by TyHil** [comment]
That's awesome to hear, thanks for using it!

**Pull request merged**
